# Generated by Django 5.0.3 on 2024-04-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_created_alter_about_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'managed': True, 'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.TextField(default='default.jpg'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
