# Generated by Django 5.0.3 on 2024-04-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="title",
            new_name="name",
        ),
    ]
