# Generated by Django 5.0.3 on 2024-03-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets',
            options={},
        ),
    ]
