# Generated by Django 5.0.3 on 2024-03-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_assets_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets',
            options={'managed': True},
        ),
    ]
