# Generated by Django 5.0.3 on 2024-04-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_rename_assets_asset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'managed': True, 'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='asset',
            name='content',
            field=models.TextField(default='default.jpg'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='title',
            field=models.TextField(max_length=200),
        ),
    ]
