[build]
builder = "DOCKERFILE"
dockerfilePath = "app/Dockerfile"

[deploy]
numReplicas = 1
startCommand = "uvicorn main:app --host 0.0.0.0 --port 80"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10