# Generated by Django 5.0.3 on 2024-03-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True},
        ),
    ]
