# Generated by Django 5.0.3 on 2024-04-01 07:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_products_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(default='default.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
